### PR TITLE
rpcc, session: Fix isClosing check in session manager watcher

### LINKED ISSUE #111: session.Manager does not properly close if connection was closed with non-nil error
#74 propagates the error which closes a connection. This causes the check in session.Manager. watch's isClosing function to fail because the cause is the original error instead of rpcc.ErrConnClosing. This prevents the Manager's goroutine from properly terminating, and it ends up spinning and continuously polling.

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #111.

### CODE REVIEW

File: session/manager.go [hunk 1]
```diff
@@ -70,6 +70,16 @@ func (m *Manager) watch(ev *sessionEvents, created <-chan *session, done, errC c
...
+			if v, ok := e.(interface{ Closed() bool }); ok && v.Closed() {
+				// Cleanup, the underlying connection was closed
+				// before the Manager and its context does not
+				// inherit from rpcc.Conn.
+				m.cancel()
+				return true
+			}
+		}
 		switch cdp.ErrorCause(err) {
 		case rpcc.ErrConnClosing, context.Canceled:
```
Comment (dgstevens) [inline session/manager.go]: rpcc.ErrConnClosing shouldn't happen here anymore, right? It should always be caught by the newly added check.

Comment (mafredri) [reply session/manager.go]: Good catch, sorry for the late response. I kind of dropped the ball on this one 😅.
